#
# This file is only used by the CI/CD pipeline to build/push images to Azure CR.
#
# For any local dev work, see docker-compose.yml and *overrides.yml. 
#

services:
  # workspaces FE (Vue app)
  frontend:
    image: ${WS_DOCKER_REGISTRY}/workspaces-frontend:${ENV}
    build:
      context: frontend
      cache_from:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-frontend:buildcache
      cache_to:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-frontend:buildcache,mode=max

      # WARNING: these get baked into the JavaScript at build time--so ARGS not ENVS
      #
      # NB: this also makes images environment-specific! (FIXME?)
      #
      args:
        VITE_TDEI_API_URL: ${WS_TDEI_API_URL}
        VITE_TDEI_USER_API_URL: ${WS_TDEI_BACKEND_URL}
        VITE_API_URL: ${WS_API_URL}
        VITE_OSM_URL: ${WS_OSM_URL}
        VITE_RAPID_URL: ${WS_RAPID_URL}
        VITE_PATHWAYS_EDITOR_URL: ${WS_PATHWAYS_EDITOR_URL}
        VITE_IMAGERY_SCHEMA: ${WS_IMAGERY_SCHEMA_URL}
        VITE_IMAGERY_EXAMPLE_URL: ${WS_IMAGERY_EXAMPLE_URL}
        VITE_LONG_FORM_QUEST_SCHEMA: ${WS_LONG_FORM_QUEST_SCHEMA_URL}
        VITE_LONG_FORM_QUEST_EXAMPLE_URL: ${WS_LONG_FORM_QUEST_EXAMPLE_URL}
        CODE_VERSION: ${CODE_VERSION}

  frontend_tag:
    extends: frontend
    image: ${WS_DOCKER_REGISTRY}/workspaces-frontend:${CODE_VERSION}

  # rapid editor
  rapid:
    image: ${WS_DOCKER_REGISTRY}/workspaces-rapid:${ENV}
    build:
      cache_from:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-rapid:buildcache
      cache_to:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-rapid:buildcache,mode=max
      context: rapid

  rapid_tag:
    extends: rapid
    image: ${WS_DOCKER_REGISTRY}/workspaces-rapid:${CODE_VERSION}

  # pathways editor
  pathways-editor:
    image: ${WS_DOCKER_REGISTRY}/workspaces-pathways-editor:${ENV}
    build:
      cache_from:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-pathways-editor:buildcache
      cache_to:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-pathways-editor:buildcache,mode=max
      context: pathways-editor

  pathways-editor_tag:
    extends: pathways-editor
    image: ${WS_DOCKER_REGISTRY}/workspaces-pathways-editor:${CODE_VERSION}

  # OSM logging proxy, for debugging only
  osm-log-proxy:
    image: ${WS_DOCKER_REGISTRY}/workspaces-osm-log-proxy:${ENV}
    build:
      cache_from:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-osm-log-proxy:buildcache
      cache_to:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-osm-log-proxy:buildcache,mode=max
      context: osm-log-proxy

  osm-log-proxy_tag:
    extends: osm-log-proxy
    image: ${WS_DOCKER_REGISTRY}/workspaces-osm-log-proxy:${CODE_VERSION}

  # proxy for JSOM
  osm-web:
    image: ${WS_DOCKER_REGISTRY}/workspaces-osm-web:${ENV}
    build:
      cache_from:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-osm-web:buildcache
      cache_to:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-osm-web:buildcache,mode=max
      context: osm-web

  osm-web_tag:
    extends: osm-web
    image: ${WS_DOCKER_REGISTRY}/workspaces-osm-web:${CODE_VERSION}

  # OSM website/OSM API
  osm-rails:
    image: ${WS_DOCKER_REGISTRY}/workspaces-osm-rails:${ENV}
    
# These have been commented out so as not to embed these variables in the images themselves
# DO NOT CHANGE THIS PLEASE.
#
#    environment:
#        RAILS_ENV: production
#        SECRET_KEY_BASE: ${WS_OSM_SECRET_KEY_BASE}
#        WS_OSM_HOST: ${WS_OSM_HOST}
#        WS_OSM_DB_HOST: ${WS_OSM_DB_HOST}
#        WS_OSM_DB_USER: ${WS_OSM_DB_USER}
#        WS_OSM_DB_PASS: ${WS_OSM_DB_PASS}
#        WS_OSM_DB_NAME: ${WS_OSM_DB_NAME}
#        WS_MAIL_NAME: ${WS_MAIL_NAME}
#        WS_MAIL_FROM: ${WS_MAIL_FROM}
#        WS_MAIL_CONTACT: ${WS_MAIL_CONTACT}
#        WS_MAIL_RETURN_PATH: ${WS_MAIL_RETURN_PATH}
#        WS_SMTP_DOMAIN: ${WS_SMTP_DOMAIN}
#        WS_SMTP_HOST: ${WS_SMTP_HOST}
#        WS_SMTP_PORT: ${WS_SMTP_PORT}
#        WS_SMTP_USER: ${WS_SMTP_USER}
#        WS_SMTP_PASS: ${WS_SMTP_PASS}
#        PIDFILE: /tmp/pids/server.pid

    build:
#      args:
#        WS_OSM_DB_HOST: ${WS_OSM_DB_HOST}
#        WS_OSM_DB_USER: ${WS_OSM_DB_USER}
#        WS_OSM_DB_PASS: ${WS_OSM_DB_PASS}
#        WS_OSM_DB_NAME: ${WS_OSM_DB_NAME}

      cache_from:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-osm-rails:buildcache
      cache_to:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-osm-rails:buildcache,mode=max
      context: osm-rails
      dockerfile: Dockerfile.prod

  osm-rails_tag:
    extends: osm-rails
    image: ${WS_DOCKER_REGISTRY}/workspaces-osm-rails:${CODE_VERSION}

  # C-accelerated OSM API
  osm-cgimap:
    image: ${WS_DOCKER_REGISTRY}/workspaces-osm-cgimap:${ENV}
    build:
      cache_from:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-osm-cgimap:buildcache
      cache_to:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-osm-cgimap:buildcache,mode=max
      context: osm-cgimap
      dockerfile: docker/ubuntu/Dockerfile2404

  osm-cgimap_tag:
    extends: osm-cgimap
    image: ${WS_DOCKER_REGISTRY}/workspaces-osm-cgimap:${CODE_VERSION}

  # tasking manager
  tasks-backend:
    image: ${WS_DOCKER_REGISTRY}/workspaces-tasks-backend:${ENV}
    build:
      cache_from:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-tasks-backend:buildcache
      cache_to:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-tasks-backend:buildcache,mode=max
      context: tasking-manager

  tasks-backend_tag:
    extends: tasks-backend
    image: ${WS_DOCKER_REGISTRY}/workspaces-tasks-backend:${CODE_VERSION}

  # leaderboard FE/backend
  leaderboard-frontend:
    image: ${WS_DOCKER_REGISTRY}/workspaces-leaderboard-frontend:${ENV}
    build:
      cache_from:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-leaderboard-frontend:buildcache
      cache_to:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-leaderboard-frontend:buildcache,mode=max
      context: ./leaderboard/frontend
      dockerfile: Dockerfile
      
      # WARNING: these get baked into the JavaScript at build time--so ARGS not ENVS
      #
      # NB: this also makes images environment-specific! (FIXME?)
      #
      args:
        VITE_TDEI_API_URL: ${WS_TDEI_API_URL}
        VITE_TDEI_USER_API_URL: ${WS_TDEI_BACKEND_URL}
        VITE_API_URL: ${WS_API_URL}
        VITE_OSM_URL: ${WS_OSM_URL}

  leaderboard-frontend_tag:
    extends: leaderboard-frontend
    image: ${WS_DOCKER_REGISTRY}/workspaces-leaderboard-frontend:${CODE_VERSION}

  leaderboard-backend:
    image: ${WS_DOCKER_REGISTRY}/workspaces-leaderboard-backend:${ENV}
    build:
      cache_from:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-leaderboard-backend:buildcache
      cache_to:
        - type=registry,ref=${WS_DOCKER_REGISTRY}/workspaces-leaderboard-backend:buildcache,mode=max
      context: ./leaderboard/backend
      dockerfile: Dockerfile

  leaderboard-backend_tag:
    extends: leaderboard-backend
    image: ${WS_DOCKER_REGISTRY}/workspaces-leaderboard-backend:${CODE_VERSION}
